### PR TITLE
fix(io): support writing to local fs via GravitinoGvfs local issue

### LINKED ISSUE #6578: Write to local file system via Gravitino fails due to incorrect multipart upload requirement
### Describe the bug

When writing data through the Gravitino Virtual File System (gvfs://) to a FILESET configured with a local file system backend, the operation fails with the error: "The source gvfs does not support multipart upload".
This occurs because Daft currently requires multipart upload capability when writing Parquet, CSV, and JSON formats via Gravitino FILESET integration. However, this requirement is inappropriate for local file systems (SourceType::File), which do not support and do not need multipart uploads.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Component(s)

Other

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qingfeng-occ**
## Changes Made

Currently, when writing data (Parquet, CSV, JSON) to a Gravitino Virtual File System (gvfs://) URI, Daft unconditionally attempts to use a multipart upload writer. This logic assumes the underlying target is an Object Store (like S3).
However, if the Gravitino FileSet is configured to point to a local file system (SourceType::File), the operation fails with:
"The source gvfs does not support multipart upload"

## Related Issues

This PR modifies the write path to resolve the actual underlying storage configuration from the Gravitino catalog before initializing the writer.
Resolve URI: When a gvfs:// URI is detected during a write operation, we now query the Gravitino client to fetch the actual physical path and storage type.

"Closes #6578"

### CODE REVIEW

**Comment by qingfeng-occ** [comment]
@greptile

File: src/daft-writers/src/storage_backend.rs [hunk 1]
```diff
@@ -156,3 +156,73 @@ impl StorageBackend for ObjectStorageBackend {
...
+
+impl GravitinoStorageBackend {
+    #[cfg(feature = "python")]
+    pub(crate) fn parse_gravitino_url_and_config(
+        root_dir: &str,
+        io_config: IOConfig,
+    ) -> DaftResult<(String, Option<IOConfig>)> {
+        let root_dir_owned = root_dir.to_string();
+
+        match tokio::runtime::Handle::try_current() {
```
Comment (desmondcheongzx) [inline src/daft-writers/src/storage_backend.rs]: The `Ok(_handle)` branch spawns a new `std::thread` and creates a full `tokio::runtime::Runtime` to run one async call. This works but is heavy.

The codebase has `RuntimeRef::block_within_async_context()` in `src/common/runtime/src/lib.rs` for exactly this case -- it spawns on the IO runtime and blocks via a oneshot channel, no new runtime needed. Used in `daft-context` and `daft-functions-uri`. The whole try_current match could collapse to:
```
let io_runtime = get_io_runtime(true);
io_runtime.block_within_async_context(async move { ... })?
```

**Comment by qingfeng-occ** [comment]
@greptile

**Comment by qingfeng-occ** [comment]
@greptile

File: src/daft-writers/src/storage_backend.rs (hunk 1 above)
Comment (qingfeng-occ) [reply src/daft-writers/src/storage_backend.rs]: @desmondcheongzx Thanks for the review! I've addressed the comments and pushed the updates. Could you please take a look when you have a moment?
