### PR TITLE
fix(flotilla): overreporting of bytes.read

### LINKED ISSUE #6761: Flotilla overreports `bytes.read` (N×) on multi-file scans
## Summary

On Flotilla, the `bytes.read` metric for a scan is inflated by roughly N× for a scan of N files. Originally observed against S3; reproduces locally against CSV files via the distributed test harness on `main`. Swordfish (local execution) reports correctly — this is Flotilla-specific.

Example from the repro test: 5 CSV files totalling 23,900 bytes on disk, Flotilla reports **119,500 bytes read** (5× overreport).

## Where the bug lives

Each Ray worker process owns one `NativeExecutor` (`src/daft-local-execution/src/run.rs`), which caches local Swordfish pipelines by `plan_fingerprint`. All scan tasks produced by a single `ScanSourceNode` share the same fingerprint, so on a given worker they share **one** `SourceNode` — and that node owns a single `IOStatsRef` shared across its per-`InputId` `SourceStats` instances (`src/daft-local-execution/src/sources/source.rs`).

`SourceStats::build_snapshot` reads `self.io_stats.load_bytes_read()` — the same atomic counter in every instance. So when the worker calls `take_input_snapshot(input_id)` for each of N scan tasks, each snapshot returns the **cumulative** bytes read by all tasks run on that worker so far. Flotilla's `StatisticsManager` sums those per-task snapshots in `SourceStats::handle_worker_node_stats` (`src/daft-distributed/src/pipeline_node/scan_source.rs:50-62`), and the totals multiply.

The actual factor depends on timing / how tasks overlap on a worker. Worst case (all tasks complete before any `try_finish`) is N×. In between it's roughly the triangular sum.

## Reproduction

There's an `#[ignore]`'d test in `src/daft-distributed/src/statistics/tests.rs`: `test_scan_source_bytes_read_multiple_files`. It uses the distributed test harness (which runs tasks through the same `SchedulerActor → Dispatcher → LocalSwordfishWorker → NativeExecutor` chain Ray workers use) and catches the bug on local CSVs.

Run locally with:

```
cargo test -p daft-distributed test_scan_source_bytes_read_multiple_files -- --ignored
```

Expected output with bug present:

```
total_bytes_on_disk = 23900, flotilla aggregated bytes_read = 119500
```

Once the fix lands, remove the `#[ignore]` attribute.

## Why local parquet doesn't reproduce

daft-io's local parquet read path returns `GetResult::File` which goes through `collect_file` — that path skips the counting reader and never calls `io_stats.mark_bytes_read`. The S3 path and the CSV local path both mark bytes, so both reproduce. The test uses CSV for convenience; the underlying bug is not format-specific.

## Likely fix directions

Candidates — any one should kill the overcount; the right choice depends on how much of the shared state Flotilla wants to preserve:

1. **Per-`InputId` `IOStatsRef` in `SourceNode`**: stop cloning the shared `IOStatsRef` into per-`InputId` `SourceStats`; give each `SourceStats` its own. The scan processor already tags morsels with `input_id`, so bytes can be attributed at the point of `mark_bytes_read`. Cleanest fix but requires threading `input_id` through the scan stream.

2. **Delta-reporting in `SourceStats::build_snapshot`**: have each per-`InputId` `SourceStats` track the `io_stats` value at its last flush and report only the delta. Avoids plumbing changes but makes `build_snapshot` stateful.

3. **Dedup in Flotilla's aggregator**: have `RuntimeNodeManager::handle_task_event` deduplicate `bytes_read` from `SourceSnapshot`s with overlapping `IOStats`. Least surgical; masks the underlying sharing.

(1) or (2) is probably what we want.

## Related

- #6697 — original statistics test infrastructure.
- #6758 — harness changes that made this test possible; also includes the ignored repro.

### PR DESCRIPTION
**Pull request by universalmind303**
## Changes Made

fixes overreporting of bytes.read by making io stats unique per inputid instead of per source. 

Explanation of bug: 

`bytes_read` counter starts at 0

task 1 reads 20mb -> bytes_read is now at 20mb.
task 2 reads 20mb -> bytes_read is now at 40mb,
task 2 reads 20mb -> bytes_read is now at 60mb,

this part is fine and working as expected, but the issue is during the snapshotting, and summing for distributed. 
Since all tasks are sharing the same count for bytes_read, the reporting becomes wrong. 
They pull from the cumulative bytes_read, not their individual bytes_read.

so
task_1 build_snapshot produces bytes_read of 20MB
task_2 build_snapshot produces bytes_read of 40MB
task_2 build_snapshot produces bytes_read of 60MB

so then when we sum those inside handle_worker_node_stats, we end up with 120MB instead of 60MB.

Fix itself is pretty straightforward. The individual tasks no longer share an io stats ref and have their own instance of it. 

## Related Issues

Closes https://github.com/Eventual-Inc/Daft/issues/6761

### CODE REVIEW

File: src/daft-local-execution/src/sources/source.rs [hunk 1]
```diff
@@ -31,38 +31,78 @@ use crate::{
 
 pub type SourceStream<'a> = BoxStream<'a, DaftResult<PipelineMessage>>;
 
+/// Per-input stats handle bundling the counters that sources record against.
+/// Cheap to clone; every holder of the same `InputStats` shares the same
+/// underlying counters.
+#[derive(Clone)]
+pub(crate) struct InputStats {
```
Comment (universalmind303) [inline src/daft-local-execution/src/sources/source.rs:39]: This was intentionally wrapped because I plan on extending this with spill stats in a subsequent PR and by wrapping iostats in this struct, we can add whatever other stats we want without having to refactor later on.

File: src/daft-local-execution/src/sources/in_memory.rs [hunk 2]
```diff
@@ -100,6 +104,7 @@ async fn forward_partition_batch(
     } else {
         for partition in partitions {
             let owned = Arc::try_unwrap(partition).unwrap_or_else(|a| (*a).clone());
+            io_stats.mark_bytes_read(owned.size_bytes());
```
Comment (samstokes) [inline src/daft-local-execution/src/sources/in_memory.rs:107]: Does it matter that `mark_bytes_read` is now (if I understand correctly) called once per micropartition rather than just once (per input?) in `get_data`? I'm not too familiar with the code structure of `Source`s so I'm not sure if that's a significant difference or not.

**Review by samstokes — APPROVED** [review]
One question about the `mark_bytes_read` logic, not blocking if you're confident it's correct.

Have you had a chance to test this on both native and flotilla runners? Would be good to confirm the fix didn't break any assumptions the native stats path had, since that path is pretty divergent from the distributed stats path.

File: src/daft-local-execution/src/sources/in_memory.rs (hunk 2 above)
Comment (universalmind303) [reply src/daft-local-execution/src/sources/in_memory.rs:107]: i (think) this is correct, I tried on about 5 different kinds of queries and they all matched my expectations. If we notice any regressions, it should be easy to catch & fix.
