### PR TITLE
  fix(io): handle schema-evolved Iceberg columns in Parquet predicate pushdown

### LINKED ISSUE #6550: queries on schema-evolved Iceberg table fail with DaftError::FieldNotFound
## Bug Description

Querying an Iceberg table with a `WHERE` clause on a column added via schema evolution                                      
  fails when some Parquet files predate the column being added.

## Error
 DaftError::ValueError Failed to bind predicate for row group pruning on                                                     
  's3://.../data/00001-1-....parquet': DaftError::FieldNotFound Column
  "<column name>" not found in schema: []  

## Steps to Reproduce                                     
                                                                                                                              
  1. Create an Iceberg table and write some Parquet files.                                                                    
  2. Add a new column via schema evolution.                                                                                   
  3. Query: `SELECT * FROM table WHERE new_col = <value>`   
                                                                                                                              
  Old files (without the column) trigger the error during predicate evaluation.                                               
   

### Expected behavior

_No response_

### Component(s)

Other

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sankarreddy-atlan**
## Changes Made

Fixes predicate evaluation against old Parquet files that predate an Iceberg schema 
evolution — i.e., the file doesn't have a column referenced in the WHERE clause. 

  ### Root cause                                            
                                                                                                                              
  When a column is absent from a Parquet file, three code paths evaluate the predicate                                        
  against it:
                                                                                                                              
  - **Row group pruning** (`prune_row_groups`): failed with `FieldNotFound` when trying                                       
    to bind a predicate that referenced a column not in the file schema.                                                      
  - **Post-read filter** (`finalize_batch`): same binding failure for the fallback filter.                                    
  - **Late-materialised row filter** (`build_row_filter`): already handled correctly —                                        
    returns `None` when any filter column is missing.                                                                         
                                                                                                                              
  The Daft optimizer additionally rewrites `col = false` as `NOT col`. After substituting                                     
  `null_lit()` for the missing column, `NOT null_lit()` hit two further bugs:                                                 
                                                                                                                              
  1. `Series::not()` attempted to downcast a `Null`-typed series to `BooleanArray`.                                           
  2. `Expr::Not::to_field()` rejected `DataType::Null` as input.                                                              
                                                                                                                              
  ### Fix                                                   
                                                                                                                              
  **Schema evolution handling** — extract `substitute_missing_cols()`, a single helper                                        
  that rewrites column references absent from the file schema to `null_lit()`. Used by
  both `prune_row_groups` and `finalize_batch`, replacing duplicated inline `transform`                                       
  logic. Missing columns evaluate to null, which propagates conservatively: row groups                                        
  are never falsely pruned, and rows are correctly excluded by the filter                                                     
  (`mask_filter` already treats null Boolean as false per SQL WHERE semantics).                                               
                                                                                                                              
  **Type system correctness** (general fixes that make null propagation work):                                                
                                                                                                                              
  - `daft-core/series/ops/not.rs`: `Series::not()` on a `Null`-typed series returns a                                         
    null `Boolean` series — correct SQL semantics (`NOT NULL = NULL`). Matches the
    existing pattern in `between.rs`.                                                                                         
  - `daft-dsl/expr/mod.rs`: `Not::to_field()` accepts `DataType::Null` and returns                                            
    `DataType::Boolean`, consistent with the above.                                                                           
  - `daft-stats/column_stats/logical.rs`: `ColumnRangeStatistics::not()` returns                                              
    `Missing` (conservative) for `Null`-typed stats, preventing incorrect row group                                           
    pruning.                                                                                                                  
                                                                                                                              
## Related Issues

- Closes #6550

### CODE REVIEW

File: src/daft-core/src/series/ops/not.rs [hunk 1]
```diff
@@ -10,6 +10,9 @@ use crate::{
 impl Not for &Series {
     type Output = DaftResult<Series>;
     fn not(self) -> Self::Output {
+        if *self.data_type() == crate::datatypes::DataType::Null {
+            return Ok(Series::full_null(self.name(), &crate::datatypes::DataType::Boolean, self.len()));
+        }
```
Comment (rchowell) [inline src/daft-core/src/series/ops/not.rs]: Nice catch. nit: let's 'use' the types instead of qualifying.

File: src/daft-dsl/src/expr/mod.rs [hunk 2]
```diff
@@ -1839,6 +1839,8 @@ impl Expr {
                 let child_field = expr.to_field(schema)?;
                 match child_field.dtype {
                     DataType::Boolean => Ok(Field::new(expr.name(), DataType::Boolean)),
+                    // NOT of a Null-typed expression produces a null Boolean (SQL: NOT NULL = NULL).
+                    DataType::Null => Ok(Field::new(expr.name(), DataType::Boolean)),
```
Comment (rchowell) [inline src/daft-dsl/src/expr/mod.rs]:
```suggestion
                    // NOT of a null-typed expression produces a null boolean (SQL-1999 6.30.2: NOT (unknown) = unknown).
                    DataType::Null => Ok(Field::new(expr.name(), DataType::Boolean)),
```

Minor edit on the wording where null->unknown in all boolean contexts. This avoids confusion with the SQL null predicate (`NOT NULL`) which is different than `NOT(x)` where x is the NULL value.

File: tests/expressions/typing/test_logical.py [hunk 3]
```diff
@@ -41,9 +41,10 @@ def test_logical_binary(binary_data_fixture, op):
 @pytest.mark.parametrize("op", [ops.invert])
 def test_logical_unary(unary_data_fixture, op):
     arg = unary_data_fixture
+    # NOT is resolvable for bool and null (NOT NULL = NULL is valid SQL).
```
Comment (rchowell) [inline tests/expressions/typing/test_logical.py]:
```suggestion
    # NOT is resolvable for bool and null; `NOT (NULL)` is valid SQL and evaluates to NULL).
```

nit to avoid 'NOT NULL' predicate

**Comment by rchowell** [comment]
You can fix the style with `pre-commit run --all-files`
