### PR TITLE
fix(io): Write metrics in close for the last batch

### LINKED ISSUE #6518: Write metrics are skipped for last table in buffer
### Describe the bug

Probably due to the `close` implementation for `TargetBatchWriter` in [batch.rs](https://github.com/Eventual-Inc/Daft/blob/main/src/daft-writers/src/batch.rs), Daft is not emitting the write metrics for the last table in buffer.

Is this intended?

### To Reproduce

Write any dataframe with in-memory size less than `parquet_target_row_group_size` to a parquet file and we will not see any write metrics during the execution. Noticed this while working on [go_emotions ](https://huggingface.co/datasets/google-research-datasets/go_emotions) dataset. Below is a simple pipeline to see the behaviour

```
import daft

daft.set_execution_config(
    parquet_target_row_group_size=128 * 1024 * 1024 # set this to 5MB and see the metric emitted
)

# read the dataset
df = daft.read_huggingface("google-research-datasets/go_emotions")

df.write_parquet(
    root_dir="data/",
    compression="snappy",
    write_mode="overwrite",
)
```

### Expected behavior

Write metrics emitted for the last table in the buffer.

### Component(s)

Built-in Functions

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kvthr**
## Changes Made

- The issue arises from `close` in [`batch.rs`](https://github.com/Eventual-Inc/Daft/blob/9a58f564225de4d385b98bf2780aeb179111259d/src/daft-writers/src/batch.rs#L206) ignoring the metrics/stats for the last batch. 
- Added final bytes to `total_physical_bytes_written` 
- In `write.rs`: Calculate the delta in final metrics and call `add_write_result`

Used Claude to plan. Verified the implementation using the same snippet in the issue and logging metric using `result._metadata.to_recordbatch().to_pylist()`

## Related Issues
Closes #6518

### CODE REVIEW

File: src/daft-writers/src/file.rs [hunk 1]
```diff
@@ -170,8 +170,9 @@ impl AsyncFileWriter for TargetFileSizeWriter {
             && let Some(result) = self.current_writer.close().await?
         {
             self.results.push(result);
-            self.bytes_per_file
-                .push(self.current_writer.bytes_written());
+            let file_bytes = self.current_writer.bytes_written();
+            self.total_physical_bytes_written += file_bytes;
+            self.bytes_per_file.push(file_bytes);
```
[the remark this answers is not in the document]
Comment (kvthr) [reply src/daft-writers/src/file.rs]: Changed the way we calculate `bytes_delta` and removed accumulation in `file.rs`

File: src/daft-writers/src/batch.rs [hunk 2]
```diff
@@ -204,8 +204,10 @@ impl AsyncFileWriter for TargetBatchWriter {
     }
 
     async fn close(&mut self) -> DaftResult<Self::Result> {
+        let remaining_size = self.buffer.size_bytes;
         if let Some(leftovers) = self.buffer.pop_all()? {
-            self.writer.write(leftovers).await?;
+            self.write_and_update_inflation_factor(leftovers, remaining_size)
+                .await?;
```
Comment (desmondcheongzx) [inline src/daft-writers/src/batch.rs]: I'm curious - what's the motivation behind this change? IIUC the inflation factor only sizes future batches, and there are no more writes after close so this update is not necessary.

Comment (kvthr) [reply src/daft-writers/src/batch.rs]: I was testing if `write_and_update_inflation_factor` was accumulating metrics but forgot to revert. I'll do that

**Review by desmondcheongzx — APPROVED** [review]
Thanks for making the changes and adding the tests! Nit as a follow-up: instead of just asserting that `assert stat_desc["value"] > 0` we can also sum up `os.path.getsize()` to assert the exact bytes written.
