### PR TITLE
[BUG] Filter out marker files from glob scan

### LINKED ISSUE #1987: Ignore Spark marker files when performing Parquet Scans
When Spark writes parquet files out it creates non-data files as part of the write.
these include `_metadata`, `_common_metadata`, `_SUCCESS`, and `*.crc` checksum files. We should instead filter these out! 

Checkout Pyarrow's implementation for this. https://github.com/apache/arrow/blob/eb7be48ef80fcecea11be29320b244df82f1cc06/python/pyarrow/parquet.py#L556

### PR DESCRIPTION
**Pull request by colin-ho**
Closes #1987

### CODE REVIEW

File: src/daft-io/src/object_store_glob.rs [hunk 1]
```diff
@@ -309,6 +309,15 @@ fn _should_return(fm: &FileMetadata) -> bool {
         {
             false
         }
+        // These are marker files used by Spark that we don't want to return
+        FileType::File
+            if fm.filepath.ends_with("_metadata")
```
Comment (jaychia) [inline src/daft-io/src/object_store_glob.rs:314]: Let's do a `.lower()` on the file names and have these stored as constants?

Ideally it should also be configurable by the user but I think we can ignore that for now.

**Review by jaychia — APPROVED** [review]

File: src/daft-io/src/object_store_glob.rs [hunk 2]
```diff
@@ -309,6 +312,14 @@ fn _should_return(fm: &FileMetadata) -> bool {
         {
             false
         }
+        // Do not return Spark marker files
+        FileType::File
+            if MARKER_SUFFIXES
+                .iter()
+                .any(|suffix| fm.filepath.to_lowercase().ends_with(suffix)) =>
```
Comment (samster25) [inline src/daft-io/src/object_store_glob.rs:319]: for `_metadata`, `_common_metadata`, and `_success` this may be bug prone. 
Imagine you have a parquet file called `image_metadata`. this would filter that file out. Instead you want to find an exact match of `filename` where `filename` is `basepath / filename` for those 3.

**Review by samster25 — APPROVED** [review]
